project1:
	g++ -g -std=c++14 ./compilecode/Project1/*.cpp -o auto_out1
project2:
	g++ -g -std=c++14 ./compilecode/Project2/*.cpp -o auto_out2
project3:
	g++ -g -std=c++14 ./compilecode/Project3/*.cpp -o auto_out3
project4:
	g++ -g -std=c++14 ./compilecode/Project2/*.cpp -o auto_out4
